CREATE TABLE ITEMS (
  id INT PRIMARY KEY,
  ITEM_NAME VARCHAR(100),
  MANUFACTURER_NAME VARCHAR(256),
  COST FLOAT,
  WEIGHT_KG FLOAT
);

CREATE TABLE MEMBER (
  id INT PRIMARY KEY,
  MEMBER_NAME VARCHAR(256),
  MEMBER_EMAIL VARCHAR(256),
  MEMBER_DOB DATE,
  MEMBER_MOBILE_NO INT
);

CREATE TABLE PURCHASE_ORDER (
  id INT PRIMARY KEY,
  MEMBER_ID INT,
  TOTAL_ITEMS_PRICE FLOAT,
  TOTAL_ITEMS_WEIGHT FLOAT
);

CREATE TABLE PURCHASE_DETAILS (
  ID INT PRIMARY KEY,
  ITEM_ID INT,
);