# Use the PostgreSQL base image
FROM postgres:latest

ENV POSTGRES_PASSWORD=Chuekueh@97
ENV POSTGRES_USER=glen

# Copy the create table script(s) into the Docker image
COPY create_tables.sql /docker-entrypoint-initdb.d/

# Expose the default PostgreSQL port
EXPOSE 5432

#Set Working Dir 
WORKDIR /Users/glen/Desktop/Glen_Chue_Govtech_Submission/Section_2

# Copy the Dockerfile and application files to the working directory
COPY . /Users/glen/Desktop/Glen_Chue_Govtech_Submission/Section_2